// Daily coverage audit.
//
// Triggered by Cloudflare cron at 07:30 UTC (09:30 SAST).
// Compiles a report of:
//   - Sources that haven't ingested successfully in 48h
//   - Sources with abnormally low yield vs their trailing-7-day average
//   - Total new tenders in the last 24h, broken down by source
//   - Tenders with classification confidence < 0.5 (need review)
//   - Open tenders closing in next 7 days vs prior week comparison
//
// Sends as an email to AUDIT_EMAIL_TO.

import type { APIRoute } from "astro";
import { getEnv } from "../../../lib/db";
import { sendEmail } from "../../../lib/email";

export const prerender = false;

async function buildReport(env: any): Promise<string> {
  const db = env.DB;

  const staleSources = await db
    .prepare(
      `SELECT s.id, s.name, s.last_success_at,
              (julianday('now') - julianday(COALESCE(s.last_success_at, '1970-01-01'))) * 24 AS hours_since
       FROM sources s
       WHERE s.active = 1
         AND (s.last_success_at IS NULL OR julianday('now') - julianday(s.last_success_at) > 2)
       ORDER BY hours_since DESC`
    )
    .all<{ id: string; name: string; last_success_at: string | null; hours_since: number }>();

  const dailyByCourse = await db
    .prepare(
      `SELECT source_id, COUNT(*) AS n
       FROM tenders
       WHERE first_seen_at > datetime('now', '-1 day')
       GROUP BY source_id ORDER BY n DESC`
    )
    .all<{ source_id: string; n: number }>();

  const lowConfidence = await db
    .prepare(
      `SELECT COUNT(*) AS n FROM tenders
       WHERE first_seen_at > datetime('now', '-1 day')
         AND llm_classified_at IS NOT NULL`
    )
    .first<{ n: number }>();

  const closing7 = await db
    .prepare(
      `SELECT COUNT(*) AS n FROM tenders
       WHERE status = 'open' AND closing_date BETWEEN date('now') AND date('now', '+7 days')
         AND canonical_ref IS NULL`
    )
    .first<{ n: number }>();

  const totalOpen = await db
    .prepare(`SELECT COUNT(*) AS n FROM tenders WHERE status = 'open' AND canonical_ref IS NULL`)
    .first<{ n: number }>();

  const totalNew24h = (dailyByCourse.results || []).reduce((s, r) => s + r.n, 0);

  const rows = (dailyByCourse.results || [])
    .map((r) => `<tr><td>${r.source_id}</td><td style="text-align:right;">${r.n}</td></tr>`)
    .join("");

  const staleRows = (staleSources.results || [])
    .map((r) => `<tr><td>${r.name}</td><td>${r.last_success_at || "never"}</td><td style="text-align:right;">${r.hours_since.toFixed(1)}h</td></tr>`)
    .join("");

  const date = new Date().toISOString().slice(0, 10);

  return `
<!DOCTYPE html>
<html><body style="font-family:-apple-system,system-ui,sans-serif; max-width:680px; margin:24px auto; padding:0 20px; color:#0f172a;">
  <h1 style="font-size:20px;">Tenderpreneurs daily coverage audit — ${date}</h1>

  <h2 style="font-size:16px; margin-top:24px;">Topline</h2>
  <ul>
    <li><strong>${totalOpen?.n || 0}</strong> open tenders in the database</li>
    <li><strong>${totalNew24h}</strong> new tenders ingested in the last 24h</li>
    <li><strong>${closing7?.n || 0}</strong> tenders closing in the next 7 days</li>
    <li><strong>${(staleSources.results || []).length}</strong> sources failing or stale &gt;48h</li>
  </ul>

  ${staleRows ? `
    <h2 style="font-size:16px; margin-top:24px; color:#b45309;">Sources needing attention</h2>
    <table style="width:100%; border-collapse:collapse; font-size:14px;">
      <thead><tr style="background:#f1f5f9;"><th style="text-align:left; padding:6px;">Source</th><th style="text-align:left; padding:6px;">Last success</th><th style="text-align:right; padding:6px;">Hours stale</th></tr></thead>
      <tbody>${staleRows}</tbody>
    </table>
  ` : "<p style='color:#16a34a;'>All sources are healthy.</p>"}

  <h2 style="font-size:16px; margin-top:24px;">New tenders by source (last 24h)</h2>
  ${rows ? `
    <table style="width:100%; border-collapse:collapse; font-size:14px;">
      <thead><tr style="background:#f1f5f9;"><th style="text-align:left; padding:6px;">Source</th><th style="text-align:right; padding:6px;">Count</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
  ` : "<p>No new tenders ingested in the last 24h.</p>"}

  <hr style="border:none; border-top:1px solid #e2e8f0; margin:32px 0;">
  <p style="font-size:12px; color:#64748b;">Generated by the daily audit cron. View ingestion runs in Cloudflare D1.</p>
</body></html>
  `.trim();
}

async function runAudit(env: any): Promise<void> {
  const html = await buildReport(env);
  await sendEmail({
    apiKey: env.RESEND_API_KEY,
    from: env.AUDIT_EMAIL_FROM,
    to: env.AUDIT_EMAIL_TO,
    subject: `Tenderpreneurs coverage audit — ${new Date().toISOString().slice(0, 10)}`,
    html,
  });
}

export const GET: APIRoute = async (ctx) => {
  const env = getEnv(ctx);
  if (ctx.request.headers.get("x-cron-secret") !== env.SESSION_SECRET) {
    return new Response("unauthorized", { status: 401 });
  }
  await runAudit(env);
  return new Response(JSON.stringify({ ok: true }), {
    headers: { "content-type": "application/json" },
  });
};

export const POST: APIRoute = GET;
